name: Omni-Workspace CI/CD - borg
'on':
  push:
    paths:
    - borg/**
  pull_request:
    paths:
    - borg/**
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Run Pipeline for borg
      run: python3 scripts/deployment_pipeline.py borg staging
